# Generated by Django 4.1.2 on 2023-08-15 09:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("rehab", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="image",
        ),
        migrations.AddField(
            model_name="blog",
            name="picture",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, upload_to="blogs"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, upload_to="services"
            ),
        ),
        migrations.AlterField(
            model_name="testimony",
            name="photo",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, upload_to="testimonies"
            ),
        ),
    ]
