# Generated by Django 4.1.2 on 2023-08-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rehab", "0003_career"),
    ]

    operations = [
        migrations.AlterField(
            model_name="career",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
