# Generated by Django 4.1.2 on 2023-08-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rehab", "0004_alter_career_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
