# Generated by Django 4.1.2 on 2023-08-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rehab", "0005_alter_blog_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="career",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
