# Generated by Django 4.1.2 on 2023-08-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rehab", "0006_alter_blog_created_alter_career_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="description",
            new_name="body",
        ),
    ]
